AWSTemplateFormatVersion: '2010-09-09'
Description: NLB
Parameters:
  SubnetId1:
    Description: Please provide the first private subnet id with outbound connectivity within the VPC you selected above.
    Type: AWS::EC2::Subnet::Id
  SubnetId2:
    Description: Please provide the second private subnet id with outbound connectivity within the VPC you selected above.
    Type: AWS::EC2::Subnet::Id
  Environment:
    Description: dev\pre\qua\prod
    Type: String
    Default: dev
    AllowedValues: ['dev','pre','prd','qua']
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network Configuration
      Parameters:
      - SubnetId1
      - SubnetId2
    ParameterLabels:
      VPCId:
        default: Target VPC for solution
      SubnetId1:
        default: Simple AD Primary Subnet
      SubnetId2:
        default: Simple AD Secondary Subnet
Resources:
  NetworkLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Join ["-" , [!Ref 'AWS::StackName', NLB,!Ref Environment]]
      Scheme: internal
      Subnets:
        - !Ref SubnetId1
        - !Ref SubnetId2
      Type: network

Outputs:
  LDAPSURL:
    Description: LDAPS Route53 Alias Target
    Value: !GetAtt NetworkLoadBalancer.DNSName