AWSTemplateFormatVersion: 2010-09-09
Description: This CF template creates cloudWatch for bill alarm,CPU utilization alarm,Recover an Amazon Elastic Compute Cloud instance

########################## Resources ###########################################
Resources:
########## SpendingAlarm: ###########
  SpendingAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: 
        'Fn::Join':
          - ''
          - - Alarm if AWS spending is over $
            - Ref: AlarmThreshold
      Namespace: AWS/Billing
      MetricName: EstimatedCharges
      Dimensions:
      - Name: Currency
        Value: USD
      Statistic: Maximum
      Period: '21600'
      EvaluationPeriods: '1'
      Threshold:
        Ref: "AlarmThreshold"
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
      - Ref: "BillingAlarmNotification"
      InsufficientDataActions:
      - Ref: "BillingAlarmNotification"
########## CPU utilization alarm ###########
  CPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: CPU alarm for my instance
      AlarmActions:
      - Ref: "logical name of an AWS::SNS::Topic resource"
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: '60'
      EvaluationPeriods: '3'
      Threshold: '90'
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: InstanceId
        Value:
          Ref: "logical name of an AWS::EC2::Instance resource"
########## Recover an Amazon Elastic Compute Cloud instance ###########
  RecoveryTestAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmDescription: Trigger a recovery when instance status check fails for 15
        consecutive minutes.
      Namespace: AWS/EC2
      MetricName: StatusCheckFailed_System
      Statistic: Minimum
      Period: '60'
      EvaluationPeriods: '15'
      ComparisonOperator: GreaterThanThreshold
      Threshold: '0'
      AlarmActions: [ !Sub "arn:aws:automate:${AWS::Region}:ec2:recover" ]
      Dimensions:
      - Name: InstanceId
        Value:
          Ref: RecoveryInstance