AWSTemplateFormatVersion: 2010-09-09
Description: This CF template creates ECR
Parameters:
  RepositoryName:
    Type: String
    Description: Repositry Name
  ScanOnPush:
    Type: Boolen
    Description: scan on push or not
    AllowedValues:
      - true
      - false

Resources:
  MyRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: !Ref RepositoryName
      ImageScanningConfiguration: 
        ScanOnPush: !Ref ScanOnPush
      EncryptionConfiguration:
        EncryptionType: AES256