AWSTemplateFormatVersion: 2010-09-09
Description: This CF template creates S3 bucket along with bucket policy. That will have different resrictions and services depending on the Dataclassification in the bucket.
Parameters:

  app:
    Description: Enter the Application Name.(Required)
    Type: String
    AllowedPattern: "[^\\s]+"
    ConstraintDescription: "application name tag min 3 and max 50 characters"
    MinLength: 3
    MaxLength: 50
  env:
    Description: select the enviroment of the resource (Required).
    Type: String
    Default: dev
    AllowedValues:
      - prod
      - stg
      - qa
      - dev


Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Tags (Mandatory)
        Parameters:
          - app
          - env



########################## Resources ###########################################

Resources:

  S3KMSKey:
#    DependsOn:
#      - WorkItemBucketBackupRole
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Id: access-account
        Statement:
          - Sid: 'Allow direct access to key metadata to the account'
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws-cn:iam::${AWS::AccountId}:root
            Action: 
#              - kms:Describe*
#              - kms:Get*
#              - kms:List*
               - kms:*
            Resource: '*'
          - Sid: 'Allow access through S3 for all principals in the account that are authorized to use S3'
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: '*'
            Condition:
              StringEquals:
                "kms:CallerAccount": !Sub ${AWS::AccountId}
                "kms:ViaService": "s3.cn-north-1.amazonaws.com"


  KeyAlias:
    DependsOn:
      - S3KMSKey
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/iws3
      TargetKeyId: !Ref S3KMSKey           


  EFSKMSKey:
#    DependsOn:
#      - WorkItemBucketBackupRole
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Version: 2012-10-17
        Id: access-account
        Statement:
          - Sid: 'Allow direct access to key metadata to the account'
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws-cn:iam::${AWS::AccountId}:root
            Action: 
#              - kms:Describe*
#              - kms:Get*
#              - kms:List*
               - kms:*
            Resource: '*'
          - Sid: 'Allow access through S3 for all principals in the account that are authorized to use S3'
            Effect: Allow
            Principal:
              AWS: '*'
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource: '*'
            Condition:
              StringEquals:
                "kms:CallerAccount": !Sub ${AWS::AccountId}
                "kms:ViaService": "elasticfilesystem.cn-north-1.amazonaws.com"


  EFSKeyAlias:
    DependsOn:
      - EFSKMSKey
    Type: AWS::KMS::Alias
    Properties:
      AliasName: alias/efs
      TargetKeyId: !Ref EFSKMSKey



############################## Outputs #########################################
Outputs:
  S3KMSKeyName:
    Description: S3 bucket Name
    Value: !Ref S3KMSKey